-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE social_following
-- DROP CONSTRAINT IF EXISTS social_following_followee_id_fkey;
