version: '3.8'

services:
  database:
    image: postgres:14.9
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}      
    volumes:
      - pgdata:/var/lib/postgresql/data

  graphql:
    image: hasura/graphql-engine:v2.34.0
    ports:
      - "8080:8080"
    depends_on:
      - database
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}

volumes:
  pgdata:



