version: '3.8'

services:
  database:
    container_name: masterbots-postgres
    image: postgres:14.5
    volumes:
      - masterbots-pgdata:/var/lib/postgresql/data_bitcash
    ports:
      - "5433:5433"
    environment:
      PGPORT: 5433
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: masterbots

  hasura:
    container_name: masterbots-hasura
    build: ./apps/hasura
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database
    env_file:
      - .env
    environment:
      # ? LOCAL
      HASURA_GRAPHQL_DATABASE_URL: "postgres://user:pass@database:5433/masterbots?sslmode=disable"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 100
      HASURA_GRAPHQL_SERVER_PORT: 8080
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: naming_convention
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: graphql-default
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key":"cea97d37d22705812fd5244b99a7fa7d4f356235c44c8be30ae9699979f46bff"}'

volumes:
  masterbots-pgdata:



