version: "3"

dotenv: [".env"]
silent: true

tasks:
  console:
    cmds:
      - hasura console --project $MASTERBOTS_HASURA

  boot:
    cmds:
      - docker-compose up -d --build database
      - sleep 10
      - docker-compose up -d --build hasura
      - echo "Waiting 30s for postgres and hasura to start ..."
      - sleep 30
      - task migrate

  reboot:
    cmds:
      - task down
      - task boot

  seed:
    cmds:
      - hasura seeds apply --project $MASTERBOTS_HASURA

  up:
    cmds:
      - docker-compose up -d --build

  down:
    cmds:
      - docker-compose down -v --remove-orphans

  migrate:
    cmds:
      - hasura migrate apply --project $MASTERBOTS_HASURA
      - hasura metadata apply --project $MASTERBOTS_HASURA

  reload:
    cmds:
      - task down
      - docker-compose up -d postgres
      - sleep 5
      - docker-compose up -d --build
      - docker-compose logs -f hasura
