// this helps displaying camelCase names in ui
export const botNames = new Map([
  ['healthbot', 'HealthBot'],
  ['techbot', 'TechBot'],
  ['moneybot', 'MoneyBot'],
  ['edubot', 'EduBot'],
  ['scibot', 'SciBot'],
  ['travelbot', 'TravelBot'],
  ['mediabot', 'MediaBot'],
  ['jobbot', 'JobBot'],
  ['homebot', 'HomeBot'],
  ['lawbot', 'LawBot'],
  ['biobuddybot', 'BioBuddyBot'],
  ['chemwizbot', 'ChemWizBot'],
  ['buildbot', 'BuildBot'],
  ['contractbot', 'ContractBot'],
  ['consumerchampbot', 'ConsumerChampBot'],
  ['workrightsbot', 'WorkRightsBot'],
  ['venturelawbot', 'VentureLawBot'],
  ['skillsyncbot', 'SkillSyncBot'],
  ['preptalkbot', 'PrepTalkBot'],
  ['resumebot', 'ResuMeBot'],
  ['handybot', 'HandyBot'],
  ['decorbot', 'DecorBot'],
  ['tunetailor', 'TuneTailor'],
  ['flickfinderbot', 'FlickFinderBot'],
  ['thrillbot', 'ThrillBot'],
  ['wanderbot', 'WanderBot'],
  ['techpulsebot', 'TechPulseBot'],
  ['codeguru', 'CodeGuru'],
  ['lingobot', 'LingoBot'],
  ['budgetbot', 'BudgetBot'],
  ['debtzero', 'DebtZero'],
  ['wealthwizbot', 'WealthWizBot'],
  ['gymgenie', 'GymGenie'],
  ['diedocbot', 'DieDocBot'],
  ['acienthelbalbot', 'AncientHelbalBot'],
])
