-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."chatbot" add column "pro_exclusive" boolean
--  null default 'false';
