/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ves5QLfs0Vt
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Input } from '@/components/ui/input'
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select
} from '@/components/ui/select'
import { Button } from '@/components/ui/button'

export function AccountForm() {
  return (
    <div className="max-w-2xl mx-auto p-6 bg-white rounded-lg shadow-md">
      <h1 className="text-2xl font-semibold">Account</h1>
      <p className="text-sm text-gray-600">
        Update your account settings. Set your preferred language and timezone.
      </p>
      <div className="mt-6 border-t border-gray-200 pt-4">
        <label
          className="block text-sm font-medium text-gray-700"
          htmlFor="name"
        >
          Name
        </label>
        <Input className="mt-1 mb-2" id="name" placeholder="Your name" />
        <p className="text-xs text-gray-500">
          This is the name that will be displayed on your profile and in emails.
        </p>
      </div>
      <div className="mt-4">
        <label
          className="block text-sm font-medium text-gray-700"
          htmlFor="dob"
        >
          Date of birth
        </label>
        <Input
          className="mt-1 mb-2"
          id="dob"
          placeholder="Pick a date"
          type="date"
        />
        <p className="text-xs text-gray-500">
          Your date of birth is used to calculate your age.
        </p>
      </div>
      <div className="mt-4">
        <label
          className="block text-sm font-medium text-gray-700"
          htmlFor="language"
        >
          Language
        </label>
        <Select>
          <SelectTrigger>
            <SelectValue placeholder="Select language" />
          </SelectTrigger>
          <SelectContent position="popper">
            <SelectItem value="english">English</SelectItem>
            <SelectItem value="spanish">Spanish</SelectItem>
            <SelectItem value="french">French</SelectItem>
            <SelectItem value="german">German</SelectItem>
          </SelectContent>
        </Select>
        <p className="text-xs text-gray-500">
          This is the language that will be used in the dashboard.
        </p>
      </div>
      <div className="mt-6">
        <Button>Update account</Button>
      </div>
    </div>
  )
}
