/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/b8COGUcouxp
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select
} from '@/components/ui/select'
import { Button } from '@/components/ui/button'

export function AppearanceForm() {
  return (
    <div className="max-w-4xl mx-auto p-6 bg-white rounded-lg shadow-md">
      <h1 className="text-2xl font-semibold">Appearance</h1>
      <p className="text-sm text-gray-600 mt-1 mb-6">
        Customize the appearance of the app. Automatically switch between day
        and night themes.
      </p>
      <div className="border-t border-gray-200 pt-4">
        <div className="mb-4">
          <label
            className="block text-sm font-medium text-gray-700 mb-1"
            htmlFor="font"
          >
            Font
          </label>
          <Select>
            <SelectTrigger id="font">
              <SelectValue placeholder="Inter" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="inter">Inter</SelectItem>
              <SelectItem value="roboto">Roboto</SelectItem>
              <SelectItem value="arial">Arial</SelectItem>
            </SelectContent>
          </Select>
          <p className="text-xs text-gray-500 mt-2">
            Set the font you want to use in the dashboard.
          </p>
        </div>
        <div className="mb-6">
          <label
            className="block text-sm font-medium text-gray-700 mb-1"
            htmlFor="theme"
          >
            Theme
          </label>
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-white border rounded-lg p-4 shadow-sm">
              <div className="h-4 bg-gray-200 rounded mb-2" />
              <div className="h-4 bg-gray-200 rounded mb-2" />
              <div className="h-4 bg-gray-200 rounded mb-2" />
              <div className="h-4 bg-gray-200 rounded" />
            </div>
            <div className="bg-gray-800 border border-gray-700 rounded-lg p-4 shadow-sm">
              <div className="h-4 bg-gray-400 rounded mb-2" />
              <div className="h-4 bg-gray-400 rounded mb-2" />
              <div className="h-4 bg-gray-400 rounded mb-2" />
              <div className="h-4 bg-gray-400 rounded" />
            </div>
          </div>
          <div className="flex justify-between text-xs font-medium text-gray-700 mt-2">
            <span>Light</span>
            <span>Dark</span>
          </div>
        </div>
        <Button className="w-full">Update preferences</Button>
      </div>
    </div>
  )
}
