/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tM1vUHU50RE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"

export function DisplayForm() {
  return (
    <div className="bg-[#1e1e1e] text-white p-8 w-full max-w-lg">
      <h1 className="text-3xl font-bold mb-2">Display</h1>
      <p className="mb-6">Turn items on or off to control what's displayed in the app.</p>
      <hr className="border-gray-600 mb-6" />
      <h2 className="text-2xl font-semibold mb-4">Sidebar</h2>
      <p className="mb-6">Select the items you want to display in the sidebar.</p>
      <div className="space-y-4 mb-8">
        <div className="flex items-center space-x-2">
          <Checkbox defaultChecked id="recents" />
          <label className="text-sm font-medium leading-none" htmlFor="recents">
            Recents
          </label>
        </div>
        <div className="flex items-center space-x-2">
          <Checkbox defaultChecked id="home" />
          <label className="text-sm font-medium leading-none" htmlFor="home">
            Home
          </label>
        </div>
        <div className="flex items-center space-x-2">
          <Checkbox id="applications" />
          <label className="text-sm font-medium leading-none" htmlFor="applications">
            Applications
          </label>
        </div>
        <div className="flex items-center space-x-2">
          <Checkbox id="desktop" />
          <label className="text-sm font-medium leading-none" htmlFor="desktop">
            Desktop
          </label>
        </div>
        <div className="flex items-center space-x-2">
          <Checkbox id="downloads" />
          <label className="text-sm font-medium leading-none" htmlFor="downloads">
            Downloads
          </label>
        </div>
        <div className="flex items-center space-x-2">
          <Checkbox id="documents" />
          <label className="text-sm font-medium leading-none" htmlFor="documents">
            Documents
          </label>
        </div>
      </div>
      <Button className="w-full">Update display</Button>
    </div>
  )
}
