/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/lQ1mzQshIin
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Switch } from "@/components/ui/switch"
import { Button } from "@/components/ui/button"

export function NotificationsForm() {
  return (
    <div className="bg-white text-black p-8">
      <h1 className="text-2xl font-semibold mb-2">Notifications</h1>
      <p className="mb-6 text-sm">Configure how you receive notifications.</p>
      <div className="border-t border-b border-gray-200 py-4 mb-6">
        <fieldset>
          <legend className="text-lg font-medium mb-3">Notify me about...</legend>
          <div className="space-y-2">
            <div className="flex items-center">
              <input className="mr-2" id="all-messages" name="notification" type="radio" />
              <label className="text-sm" htmlFor="all-messages">
                All new messages
              </label>
            </div>
            <div className="flex items-center">
              <input className="mr-2" id="direct-messages" name="notification" type="radio" />
              <label className="text-sm" htmlFor="direct-messages">
                Direct messages and mentions
              </label>
            </div>
            <div className="flex items-center">
              <input className="mr-2" id="nothing" name="notification" type="radio" />
              <label className="text-sm" htmlFor="nothing">
                Nothing
              </label>
            </div>
          </div>
        </fieldset>
      </div>
      <h2 className="text-lg font-medium mb-4">Email Notifications</h2>
      <div className="space-y-6 mb-6">
        <div className="flex justify-between items-center">
          <div>
            <h3 className="font-medium">Communication emails</h3>
            <p className="text-sm text-gray-600">Receive emails about your account activity.</p>
          </div>
          <Switch id="communication-emails" />
        </div>
        <div className="flex justify-between items-center">
          <div>
            <h3 className="font-medium">Marketing emails</h3>
            <p className="text-sm text-gray-600">Receive emails about new products, features, and more.</p>
          </div>
          <Switch id="marketing-emails" />
        </div>
        <div className="flex justify-between items-center">
          <div>
            <h3 className="font-medium">Social emails</h3>
            <p className="text-sm text-gray-600">Receive emails for friend requests, follows, and more.</p>
          </div>
          <Switch id="social-emails" />
        </div>
        <div className="flex justify-between items-center">
          <div>
            <h3 className="font-medium">Security emails</h3>
            <p className="text-sm text-gray-600">Receive emails about your account activity and security.</p>
          </div>
          <Switch id="security-emails" />
        </div>
      </div>
      <div className="border-t border-gray-200 pt-4">
        <div className="flex items-center justify-between">
          <div>
            <input className="mr-2" id="mobile-settings" type="checkbox" />
            <label className="text-sm" htmlFor="mobile-settings">
              Use different settings for my mobile devices
            </label>
            <p className="text-xs text-gray-600">
              You can manage your mobile notifications in the mobile settings page.
            </p>
          </div>
        </div>
        <div className="mt-6">
          <Button>Update notifications</Button>
        </div>
      </div>
    </div>
  )
}
