/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/egzate5BNPw
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export function ProfileForm() {
  return (
    <div className="flex-1">
      <div className="mb-6">
        <h2 className="text-xl font-semibold">Profile</h2>
        <p className="text-gray-400 mt-1">
          This is how others will see you on the site.
        </p>
      </div>
      <div className="grid gap-6">
        <div>
          <label className="block text-sm font-medium mb-1" htmlFor="username">
            Username
          </label>
          <div className="flex">
            <input
              className="bg-gray-800 text-white w-full px-3 py-2 rounded"
              id="username"
              readOnly
              type="text"
              value="shadcn"
            />
            <button className="ml-2 text-blue-500 hover:text-blue-400">
              <FileEditIcon className="w-5 h-5" />
            </button>
          </div>
          <p className="text-gray-400 mt-1 text-sm">
            This is your public display name. It can be your real name or a
            pseudonym. You can only change this once every 30 days.
          </p>
        </div>
        <div>
          <label className="block text-sm font-medium mb-1" htmlFor="email">
            Email
          </label>
          <select
            className="bg-gray-800 text-white w-full px-3 py-2 rounded"
            id="email"
          >
            <option>Select a verified email to display</option>
          </select>
          <p className="text-gray-400 mt-1 text-sm">
            You can manage verified email addresses in your email settings.
          </p>
        </div>
        <div>
          <label className="block text-sm font-medium mb-1" htmlFor="bio">
            Bio
          </label>
          <textarea
            className="bg-gray-800 text-white w-full px-3 py-2 rounded"
            id="bio"
            rows={3}
          >
            I own a computer.
          </textarea>
          <p className="text-gray-400 mt-1 text-sm">
            You can @mention other users and organizations to link to them.
          </p>
        </div>
        <div>
          <label className="block text-sm font-medium mb-1" htmlFor="urls">
            URLs
          </label>
          <input
            className="bg-gray-800 text-white w-full px-3 py-2 rounded mb-2"
            id="urls"
            placeholder="https://shadcn.com"
            type="url"
          />
          <input
            className="bg-gray-800 text-white w-full px-3 py-2 rounded mb-2"
            placeholder="http://twitter.com/shadcn"
            type="url"
          />
          <button className="text-blue-500 hover:text-blue-400">Add URL</button>
        </div>
        <div>
          <button className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded">
            Update profile
          </button>
        </div>
      </div>
    </div>
  )
}

function FileEditIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z" />
    </svg>
  )
}
