-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."domain_enum" add column "added" timestamptz
--  null default now();
