import {
  Cloud,
  CreditCard,
  Eye,
  Github,
  Keyboard,
  LifeBuoy,
  LogOut,
  Mail,
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Settings,
  SunMedium,
  Twitter,
  User,
  UserPlus,
  Users,
  X,
  Check,
  AlertTriangle,
  AlertCircle,
  ChevronDown,
  Menu,
  Send,
  ArrowLeft,
  Search,
  ArrowRight,
  ChevronRight,
  Facebook,
  Linkedin,
  AtSign,
  Bell,
  Paperclip,
  File
} from "lucide-react"

export const LucideIcons = {
  sun: SunMedium,
  moon: Moon,
  twitter: Twitter,
  cloud: Cloud,
  creditCard: CreditCard,
  github: Github,
  keyboard: Keyboard,
  lifeBuoy: LifeBuoy,
  logOut: LogOut,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  settings: Settings,
  user: User,
  userPlus: UserPlus,
  users: Users,
  eye: Eye,
  close: X,
  check: Check,
  error: AlertCircle,
  warning: AlertTriangle,
  chevronDown: ChevronDown,
  menu: Menu,
  sendIcon: Send,
  arrowLeft: ArrowLeft,
  search: Search,
  arrowRight: ArrowRight,
  chevronRight: ChevronRight,
  facebook: Facebook,
  linkedin: Linkedin,
  threadIcon: AtSign,
  attachment: Paperclip,
  file: File,
}
