-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."message" add column "isContinued" boolean
--  null default 'false';
