-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."preference" add column "web_search" boolean
--  null default 'false';
