-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."label_chatbot_category_domain" add column "domain_id" varchar
--  null;
