-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."social_following" add column "followee_id_chatbot" integer
--  null;
