SET check_function_bodies = false;

INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (1, 1);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (1, 2);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (1, 3);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (2, 1);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (3, 2);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (4, 3);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (5, 6);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (6, 7);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (7, 8);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (8, 9);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (9, 10);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (10, 11);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (11, 12);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (1, 6);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (1, 7);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (1, 8);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (1, 9);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (1, 10);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (1, 11);
INSERT INTO public.prompt_chatbot (prompt_id, chabot_id) VALUES (1, 12);
