const canonicalPathnames = [
	'/healthcare/natural-health/healthbot',
	'/healthcare/holistic-health/holistibot',
	'/healthcare/nutrition/dietdocbot',
	'/healthcare/fitness-training/gymgenie',
	'/money/investment/moneybot',
	'/money/wealth-management/wealthwizbot',
	'/money/financial-wellness/debtzero',
	'/money/financial-planning/budgetbot',
	'/technology/computing/techbot', // updated from /technology/cybersecurity/techbot
	'/technology/software-development-architecture/codeguru',
	'/technology/technology-trends/techpulsebot',
	'/education/academic-productivity/edubot', // updated from /education/education/edubot
	'/education/academic-productivity/studyprobot',
	'/education/language-learning/lingobot',
	'/career/job-markets/jobbot',
	'/career/cover-letter-crafting/resumebot',
	'/career/interview-preparation/preptalkbot',
	'/career/career-exploration/skillsyncbot',
	'/science/science-research/scibot',
	'/science/biology/biobuddybot',
	'/science/chemistry/chemwizbot',
	'/science/robotics/buildbot', // updated from /science/electrical-engineering/buildbot
	'/travel/leisure/travelbot',
	'/travel/adventure-travel/wanderbot', // updated from /travel/travel/wanderbot
	'/travel/outdoor-activities/thrillbot',
	'/entertainment/media/mediabot', // updated from /entertainment/entertainment/mediabot
	'/entertainment/cinema/flickfinderbot',
	'/entertainment/music-curation/tunetailor',
	'/home/lifestyle/homebot',
	'/home/home-improvement/handybot',
	'/home/interior-design/decorbot',
	'/legal/bankruptcy-law/bankruptcybot',
	'/legal/legal-services/commonlawbot',
	'/legal/judicial-accountability/trusteecheckbot',
	'/legal/legal-regulations/lawbot',
	'/legal/startup-law/venturelawbot',
	'/legal/employment-law/workrightsbot',
	'/legal/consumer-rights-protection/consumerchampbot',
	'/legal/contract-law/contractbot',
	'/relationships/conflict-resolution/harmonybot',
	'/relationships/parenting/parentingbot', // updated from /relationships/child-development/parentingbot
	'/relationships/social-skills/socialqbot',
	'/sports/exercise/fitformbot',
	'/sports/sports-nutrition/fuelupbot',
	'/sports/sports-analytics/gamevisionbot',
	'/hobbies/diy-crafts/craftmasterbot',
	'/hobbies/music-education/musictutorbot',
	'/hobbies/photography/snapshotbot',
	'/startups/business-strategy/ideabot',
	'/startups/startup-financing/fundfinderbot',
	'/startups/startup-growth/blitzscalebot',
	'/startups/market-analysis/marketbot',
	'/environment/sustainable-living/greenbot',
	'/environment/wildlife-conservation/wildlifebot',
	'/environment/renewable-energy/renewabot',
	'/environment/sustainable-consumer-choices/ecochoicebot',
	'/environment/sustainable-mobility/greenriderbot',
	'/history/civilization-studies/histobot', // updated from /history/history/histobot
	'/history/civilization-studies/civbot',
	'/history/archaeology/archaeobot',
	'/history/cultural-anthropology/culturebot',
	'/philosophy/ethics/philosobot', // updated from /philosophy/philosophy/philosobot
	'/philosophy/ethics/ethicsbot',
	'/philosophy/existentialism/existentibot',
	'/philosophy/technology-ethics/techethicsbot',
	'/philosophy/biblical-studies/biblebot',
	'/real-estate/market-analysis/marketpulsebot', // updated from /real-state/market-analysis/marketpulsebot
	'/real-state/real-estate-investment/investsmartbot',
	'/real-state/home-buying-selling/homeguidebot',
	'/real-state/rental-management/rentwisebot',
	'/real-state/home-construction-design/homebuilderbot',
	'/auto/automotive-maintenance/mechanibot',
	'/auto/automotive-technology/autotechbot',
	'/auto/public-transportation/transitbot',
	'/fashion/style/stylebot', // updated from /fashion/fashion/stylebot
	'/fashion/makeup/glambot',
	'/fashion/skincare/glowbot',
	'/fashion/sustainable-fashion/ecofashionbot',
	'/food/food-systems-sustainability/growbot',
	'/food/agriculture-food-technology/agritechbot',
	'/health/nutrition-healthy-eating/nutribot',
	'/food/culinary-innovation-flavor-science/flavorbot',
	'/food/home-farming-urban-agriculture/homefarmbot',
	'/startups/startup-events-networking/eventprobot',
	'/startups/entrepreneurship-networking/socialdynamobot',
	'/home/home-entertainment-event-planning/partymaestro',
	'/home/meal-planning-home-cooking/mealprepper',
	'/home/culinary-arts-home-cooking/chefbot',
	'/health/sleep-health/sleepbot',
	'/mindfulness/mindfulness-focus/focusbot',
	'/mindfulness/therapy-mindfulness/therapybot',
	'/mindfulness/mindfulness-relaxation/calmbot',
	'/gaming/gaming-lore-narrative/lorebot',
	'/gaming/streaming-gaming/twitchbot',
	'/gaming/gaming-performance-training/aimtrainer',
	'/gaming/gaming-strategy-analysis/metamasterbot',
	'/mindfulness/emotional-intelligence-resilience/emobot',
	'/mindfulness/personal-growth-purpose/purposebot',
	'/productivity/habit-formation-productivity/habitformer',
	'/productivity/cognitive-performance-productivity/mindmasterbot',
	'/productivity/workflow-optimization-automation/workflowbot',
	'/productivity/goal-setting-achievement/goalgetterbot',
	'/productivity/time-management-productivity/timemasterbot',
	'/productivity/deep-work-flow-states/flowbot',
	'/writing/literary-analysis-writing/litbot',
	'/writing/branding-content-strategy/brandbot',
	'/writing/viral-marketing-social-media/viralbot',
	'/writing/creative-writing-storytelling/storybot',
	'/writing/content-strategy-copywriting/contentbot',
	'/technology/artificial-intelligence-machine-learning/aibot',
	'/money/macroeconomics-global-finance/macrobot',
	'/money/quantitative-trading-technical-analysis/traderbot',
	'/technology/cryptocurrency-fundamentals/cryptobot',
	'/money/crypto-trading-strategy/cryptotraderbot',
	'/health/natural-health-naturopathy/naturobot',
	'/science/biotechnology-ip-law/bioipbot',
	'/education/education-academic-advising/uniprepbot',
	'/science/biotechnology-bioengineering/biotechbot',
	'/science/chemical-biosciences/biochembot',
	'/startups/business-scaling-growth/scaleupbot',
	'/technology/agile-project-management/agilebot',
	'/technology/user-experience-design/uxdesignbot',
	'/technology/product-management-strategy/productbot',
	'/technology/technical-documentation/docsbot',
	'/technology/software-debugging-troubleshooting/debugbot',
	'/technology/version-control-repository-management/gitbot',
	'/technology/backend-development/backendbot',
	'/technology/frontend-development/frontendbot',
	'/technology/software-architecture/architechie',
	'/technology/devops-cloud-infrastructure/devopsbot',
	'/technology/blockchain-development-security/blockchainbot',
	'/food/food-science-safety/naturofoodbot',
	'/startups/startup-growth-marketing/growthhackabot',
	'/startups/brand-strategy/brandobot',
	'/startups/social-media-content-marketing/socialcontentbot',
	'/startups/paid-advertising-performance-marketing/adoptimizerbot',
	'/startups/seo-organic-growth/seomasterbot',
	'/startups/partnership-affiliate-marketing/partnerbot',
	'/startups/email-marketing-automation/emailautobot',
	'/startups/referral-viral-marketing/viralloopbot',
	'/startups/customer-retention-loyalty/retentionbot',
]

export const canonicalChatbotDomains = canonicalPathnames.map((pathname) => {
	// Split by "/" and filter out empty strings (as the string starts with a slash)
	const parts = pathname.split('/').filter(Boolean)
	const [topic, domain, chatbot] = parts
	return { name: chatbot, value: `${topic}/${domain}` } as const
})
