/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/onE9mAjSs6j
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function BotParamsForm() {
  return (
    <div className="bg-[#121212] text-white p-8 w-full h-full">
      <div className="border-b border-gray-600 pb-4 mb-6">
        <h2 className="text-xl font-semibold">Settings</h2>
      </div>
      <div className="space-y-6">
        <div>
          <label className="block text-sm font-medium mb-1" htmlFor="model">
            Model
          </label>
          <Select>
            <SelectTrigger id="model">
              <SelectValue placeholder="Select a model" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="model1">Model 1</SelectItem>
              <SelectItem value="model2">Model 2</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <label className="block text-sm font-medium mb-1" htmlFor="temperature">
            Temperature
          </label>
          <Input id="temperature" placeholder="0.4" />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium mb-1" htmlFor="top-p">
              Top P
            </label>
            <Input id="top-p" placeholder="0.7" />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1" htmlFor="top-k">
              Top K
            </label>
            <Input id="top-k" placeholder="0.0" />
          </div>
        </div>
      </div>
      <div className="border-t border-gray-600 pt-4 mt-6">
        <h2 className="text-xl font-semibold mb-6">Messages</h2>
        <div className="space-y-6">
          <div>
            <label className="block text-sm font-medium mb-1" htmlFor="role">
              Role
            </label>
            <Select>
              <SelectTrigger id="role">
                <SelectValue placeholder="System" />
              </SelectTrigger>
              <SelectContent position="popper">
                <SelectItem value="user">User</SelectItem>
                <SelectItem value="system">System</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div>
            <label className="block text-sm font-medium mb-1" htmlFor="content">
              Content
            </label>
            <Textarea id="content" placeholder="You are a..." />
          </div>
        </div>
      </div>
    </div>
  )
}
