-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."preference" add column "deep_expertise" boolean
--  null default 'false';
